[package]
name = "orbital"
version = "0.0.1"
description = "Orbital desktop shell"
authors = ["Orbital"]
edition = "2021"

[lib]
name = "orbital_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde_json = "1"
base64 = "0.22"
